### ISSUE TITLE
Error Code 500 on GET configuration_items

### ISSUE THREAD

**Issue by Bardzik** [jbbarth/redmine_cmdb#4]
Hi!

The plugin returns a 500 on GET configuration_items when no CI are present in CMDB.
Redmine log:

`Started GET "/configuration_items/1.json" for 172.21.0.1 at 2019-12-11 09:53:58 +0000
Processing by ConfigurationItemsController#show as JSON
  Parameters: {"id"=>"1"}
  Current user: anonymous
  Rendered plugins/redmine_cmdb/app/views/configuration_items/show.api.rsb (111.0ms)
Completed 500 Internal Server Error in 114ms (ActiveRecord: 1.1ms)

ActionView::Template::Error (undefined method `id' for nil:NilClass):
    1: api.configuration_item do
    2:   %w(id name url description item_type cmdb_identifier).each do |field|
    3:     api.send(field, @configuration_item.send(field).to_s)
    4:   end
    5:   api.active @configuration_item.active?
    6: end
  plugins/redmine_cmdb/app/views/configuration_items/show.api.rsb:3:in `block (3 levels) in _47467a5f51e736c19392819f11c38787'
  plugins/redmine_cmdb/app/views/configuration_items/show.api.rsb:2:in `each'
  plugins/redmine_cmdb/app/views/configuration_items/show.api.rsb:2:in `block (2 levels) in _47467a5f51e736c19392819f11c38787'
  lib/redmine/views/builders/structure.rb:74:in `method_missing'
  plugins/redmine_cmdb/app/views/configuration_items/show.api.rsb:1:in `block in _47467a5f51e736c19392819f11c38787'
  lib/redmine/views/builders.rb:31:in `for'
  plugins/redmine_cmdb/app/views/configuration_items/show.api.rsb:1:in `_47467a5f51e736c19392819f11c38787'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
`

Furthermore, some use cases would be more then useful in description of your plugin.

**Comment by jbbarth** [comment]
Sorry this plugin is not maintained anymore, I can only take requests from former colleagues who still use it. I’m leaving the issue open in case anyone wants to fix or take over the repo
